CREATE TABLE IF NOT EXISTS "user" (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(255) NOT NULL UNIQUE,
    first_name      VARCHAR(100),
    last_name       VARCHAR(100),
    phone           VARCHAR(20),
    address_street  VARCHAR(100),
    address_city    VARCHAR(100),
    address_zip     VARCHAR(20),
    address_country VARCHAR(50),
    avatar_url      VARCHAR(1000),
    password_hash   VARCHAR(255) NOT NULL,
    tenant_id       BIGINT NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMP NOT NULL,
    updated_at      TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS user_role (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  BIGINT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    role     VARCHAR(20) NOT NULL
);
